### ISSUE TITLE
Build Stuck for Linksys MX4300

### ISSUE THREAD

**Issue by feiyax** [qosmio/openwrt-ipq#13]
Building for MX4300, but it seems stuck somewhere during the build and it won't finish.

I'm at: 

> `commit edaebc63cdaa9be677a8f0b8d9f67702325ca8cb (ipq-qosmio/qualcommax-6.x-nss-mx4300)` 

I'm building inside a docker environment as this dockerfile's, which came from openwrt wiki: 
[Dockerfile.debian.txt](https://github.com/user-attachments/files/17369778/Dockerfile.debian.txt)

I'm using those config: 
[config.txt](https://github.com/user-attachments/files/17369780/config.txt)

Those are the logs out of a retry with `make -j1 V=sc`: 
[log.1.txt](https://github.com/user-attachments/files/17369781/log.1.txt)

I don'e see any obvious error message from logs, except that my terminal just stuck there for hours without CPU usage. Any idea what's going on with my build? Thanks.

**Comment by tofu951753** [comment]
Try posting your question here instead https://forum.openwrt.org/t/qualcommax-nss-build/148529/4076

Are you creating a debian instance using docker and just execing into it to build it?
